In [11]:
import pandas as pd
import datetime as dt
import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv('../data/online_retail_II.csv')
print(df.shape)
df.head()

(1067371, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [13]:
print(df.dtypes)
print("\nNull values:\n", df.isnull().sum())

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

Null values:
 Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [14]:
# Drop rows with no customer
df = df.dropna(subset=['Customer ID'])

# Remove cancellations (invoices starting with C)
df = df[~df['Invoice'].astype(str).str.startswith('C')]

# Remove bad quantities and prices
df = df[df['Quantity'] > 0]
df = df[df['Price'] > 0]

# Fix data types
df['Customer ID'] = df['Customer ID'].astype(int)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print("Clean dataset shape:", df.shape)

Clean dataset shape: (805549, 8)

In [15]:
# Revenue per transaction
df['TotalPrice'] = df['Quantity'] * df['Price']

# Date parts for Tableau later
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['MonthYear'] = df['InvoiceDate'].dt.to_period('M').astype(str)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice,Year,Month,MonthYear
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,2009-12

In [16]:
df.to_csv('../data/online_retail_clean.csv', index=False)
print("✅ Saved to data/online_retail_clean.csv")

✅ Saved to data/online_retail_clean.csv